scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithms:
        selection:
            name: random
        match:
            name: match
cluster:
    name: keebler
    secret: 3a36e53d-ea00-467d-8d42-fa80cb9d58d8
graphdatabase:
    name: memgraph
    host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
