scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithms:
        selection:
            name: random
        match:
            name: match
cluster:
    name: keebler
    secret: a38e8008-c5ef-4803-821f-4c930d366a3c
graphdatabase:
    name: memgraph
    host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
