scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithms:
        selection:
            name: constraint
            options: 
                # This is a list of priorities. If the first returns no matches we try the second, etc.
                priorities: |
                  - priority: 1 
                    steps:
                    - filter: "nodes_free > 0"
                    - calc: "build_cost=(cost_per_node_hour * (memory_per_node * seconds_per_gb)/60/60))"
                    - sort_descending: build_cost 
                    - select: random
                  - priority: 2
                    steps:
                    - filter: "nodes_free > 0"
                    - calc: "memory_min=min(100, memory_per_node - 100)"
                    - calc: "build_cost=(cost_per_node_hour * (memory_min * seconds_per_gb)/60/60))"
                    - sort_descending: build_cost 
                    - select: random
        match:
            name: match
cluster:
    name: keebler
    secret: 4a193104-d7fa-460a-a13d-9482173eb85d
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
    options:
        host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
