scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithm:
        name: random
cluster:
    name: keebler
    secret: d6aa12a2-cbff-4504-8a0b-1b36e8796ed8
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
    options:
        host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
