scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithms:
        selection:
            name: constraint
            options:
                key: value
        match:
            name: match
cluster:
    name: keebler
    secret: 4a193104-d7fa-460a-a13d-9482173eb85d
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
    options:
        host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
