scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithms:
        selection:
            name: random
        match:
            name: match
cluster:
    name: keebler
    secret: a5a8ebd8-6b22-44d4-aafe-6e81f92124ce
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
    options:
        host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
