scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithms:
        selection:
            name: random
        match:
            name: match
cluster:
    name: keebler
    secret: e8f9ff3b-80be-4d5e-8e71-2564f08602cf
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
    options:
        host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
