scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithm:
        name: random
cluster:
    name: keebler
    secret: edfae545-08a5-4d20-8ff9-ed16e33a786b
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
    options:
        host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
