scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithms:
        selection:
            name: random
        match:
            name: match
cluster:
    name: keebler
    secret: e00e76d7-b77d-4954-8312-64b321b890c3
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
    options:
        host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
