scheduler:
    secret: chocolate-cookies
    name: keebler
    algorithms:
        selection:
            name: random
        match:
            name: match
cluster:
    name: keebler
    secret: 79643f8e-6408-4cd1-bd1a-76aa499d5864
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
    options:
        host: 127.0.0.1:50051
clusters:
    - name: keebler
      token: rainbow
