// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: memory.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MemoryGraphClient is the client API for MemoryGraph service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemoryGraphClient interface {
	Satisfy(ctx context.Context, in *SatisfyRequest, opts ...grpc.CallOption) (*SatisfyResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Response, error)
}

type memoryGraphClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryGraphClient(cc grpc.ClientConnInterface) MemoryGraphClient {
	return &memoryGraphClient{cc}
}

func (c *memoryGraphClient) Satisfy(ctx context.Context, in *SatisfyRequest, opts ...grpc.CallOption) (*SatisfyResponse, error) {
	out := new(SatisfyResponse)
	err := c.cc.Invoke(ctx, "/service.MemoryGraph/Satisfy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryGraphClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/service.MemoryGraph/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryGraphServer is the server API for MemoryGraph service.
// All implementations must embed UnimplementedMemoryGraphServer
// for forward compatibility
type MemoryGraphServer interface {
	Satisfy(context.Context, *SatisfyRequest) (*SatisfyResponse, error)
	Register(context.Context, *RegisterRequest) (*Response, error)
	mustEmbedUnimplementedMemoryGraphServer()
}

// UnimplementedMemoryGraphServer must be embedded to have forward compatible implementations.
type UnimplementedMemoryGraphServer struct {
}

func (UnimplementedMemoryGraphServer) Satisfy(context.Context, *SatisfyRequest) (*SatisfyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Satisfy not implemented")
}
func (UnimplementedMemoryGraphServer) Register(context.Context, *RegisterRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedMemoryGraphServer) mustEmbedUnimplementedMemoryGraphServer() {}

// UnsafeMemoryGraphServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryGraphServer will
// result in compilation errors.
type UnsafeMemoryGraphServer interface {
	mustEmbedUnimplementedMemoryGraphServer()
}

func RegisterMemoryGraphServer(s grpc.ServiceRegistrar, srv MemoryGraphServer) {
	s.RegisterService(&MemoryGraph_ServiceDesc, srv)
}

func _MemoryGraph_Satisfy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatisfyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryGraphServer).Satisfy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.MemoryGraph/Satisfy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryGraphServer).Satisfy(ctx, req.(*SatisfyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryGraph_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryGraphServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.MemoryGraph/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryGraphServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryGraph_ServiceDesc is the grpc.ServiceDesc for MemoryGraph service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryGraph_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.MemoryGraph",
	HandlerType: (*MemoryGraphServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Satisfy",
			Handler:    _MemoryGraph_Satisfy_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _MemoryGraph_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memory.proto",
}
