scheduler:
    secret: chocolate-cookies
    name: spack-builder
    algorithms:
        selection:
            name: random
        match:
            name: match
cluster:
    name: spack-builder
    secret: 37e5b798-189f-4c38-bc1c-0a14877acbcf
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
clusters:
    - name: spack-builder
      token: rainbow
