scheduler:
    secret: chocolate-cookies
    name: spack-builder
    algorithms:
        selection:
            name: random
        match:
            name: match
cluster:
    name: spack-builder
    secret: bd72a288-cc3d-4659-910b-d665fd95f1a3
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
clusters:
    - name: spack-builder
      token: rainbow
