scheduler:
    secret: chocolate-cookies
    name: spack-builder
    algorithms:
        selection:
            name: random
        match:
            name: range
cluster:
    name: spack-builder
    secret: e4de434d-3e32-4950-be65-a31db3824e26
graphdatabase:
    name: memory
    host: 127.0.0.1:50051
clusters:
    - name: spack-builder
      token: rainbow
